// 编辑器主题，不引入则报错
import 'http://bj.readforchina.com/tinymce/5.10.2/themes/silver/theme.min.js'
// 引入编辑器图标icon，不引入则不显示对应图标
import 'http://bj.readforchina.com/tinymce/5.10.2/icons/default/icons.min.js'
// 引入编辑器插件
// 高级列表
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/advlist/plugin.min.js'
// 锚点
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/anchor/plugin.min.js'
// 自动链接
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/autolink/plugin.min.js'
// 编辑器高度自适应,注：plugins里引入此插件时，Init里设置的height将失效
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/autoresize/plugin.min.js'
// 自动存稿
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/autosave/plugin.min.js'
// 特殊字符
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/charmap/plugin.min.js'
// 编辑源码
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/code/plugin.min.js'
// 文字方向
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/directionality/plugin.min.js'
// 表情
// import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/emoticons/plugin.min.js'
// 文档属性
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/fullpage/plugin.min.js'
// 全屏
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/fullscreen/plugin.min.js'
// 帮助
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/help/plugin.min.js'
// 水平分割线
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/hr/plugin.min.js'
// 插入编辑图片
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/image/plugin.min.js'
// 引入css
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/importcss/plugin.min.js'
// 插入日期时间
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/insertdatetime/plugin.min.js'
// 超链接
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/link/plugin.min.js'
// 插入不间断空格
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/nonbreaking/plugin.min.js'
// 插入分页符
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/pagebreak/plugin.min.js'
// 粘贴插件
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/paste/plugin.min.js'
// 预览
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/preview/plugin.min.js'
// 快速工具栏
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/quickbars/plugin.min.js'
// 保存
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/save/plugin.min.js'
// 查找替换
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/searchreplace/plugin.min.js'
// 切入切出，按tab键切出编辑器，切入页面其他输入框中
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/tabfocus/plugin.min.js'
// 表格
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/table/plugin.min.js'
// 文字颜色
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/textcolor/plugin.min.js'
// 快速排版
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/textpattern/plugin.min.js'
// 目录生成器
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/toc/plugin.min.js'
// 显示元素范围
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/visualblocks/plugin.min.js'
// 显示不可见字符
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/visualchars/plugin.min.js'
// 字数统计
import 'http://bj.readforchina.com/tinymce/5.10.2/plugins/wordcount/plugin.min.js'
